name: 'Code Coverage Summary'
author: 'Irongut <murray.dave@outlook.com>'
description: 'A GitHub Action that reads Cobertura format code coverage files and outputs a text or markdown summary.'
branding:
  icon: book-open
  color: purple
inputs:
  filename:
    description: 'A comma separated list of code coverage files to analyse. Also supports using glob patterns to match multiple files.'
    required: true
  badge:
    description: 'Include a Line Rate coverage badge in the output using shields.io - true / false (default).'
    required: false
    default: 'false'
  fail_below_min:
    description: 'Fail if overall Line Rate below lower threshold - true / false (default).'
    required: false
    default: 'false'
  format:
    description: 'Output Format - markdown or text (default).'
    required: false
    default: 'text'
  hide_branch_rate:
    description: 'Hide Branch Rate values in the output - true / false (default).'
    required: false
    default: 'false'
  hide_complexity:
    description: 'Hide Complexity values in the output - true / false (default).'
    required: false
    default: 'false'
  indicators:
    description: 'Include health indicators in the output - true (default) / false.'
    required: false
    default: 'true'
  output:
    description: 'Output Type - console (default), file or both. Also supports github output.'
    required: false
    default: 'console'
  thresholds:
    description: 'Threshold percentages for badge and health indicators, lower threshold can also be used to fail the action.'
    required: false
    default: '50 75'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/irongut/codecoveragesummary:v1.3.0'
  args:
    - '--files'
    - ${{ inputs.filename }}
    - '--badge'
    - ${{ inputs.badge }}
    - '--fail'
    - ${{ inputs.fail_below_min }}
    - '--format'
    - ${{ inputs.format }}
    - '--hidebranch'
    - ${{ inputs.hide_branch_rate }}
    - '--hidecomplexity'
    - ${{ inputs.hide_complexity }}
    - '--indicators'
    - ${{ inputs.indicators }}
    - '--output'
    - ${{ inputs.output }}
    - '--thresholds'
    - ${{ inputs.thresholds }}
